name: Deploy to Firebase Hosting on Push

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # If you don't have a build step, remove this line
      - run: npm ci && npm run build || echo "No build step, skipping..."

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_INTELLIPARK2025_327E9 }}
          projectId: intellipark2025-327e9
